name: Runner Test
on:
    workflow_dispatch:
        inputs:
            tag:
                description: 'Tag to run'
                required: false
                default: ''

            env:
                description: 'Environment to run'
                required: true
                type: choice
                options:
                    - test
                    - prod

jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'temurin'

            - name: Run Test
              run: |
                mvn verify ${{ inputs.tag != '' && format('-Dcucumber.filter.tags="{0}"', inputs.tag) || '' }} -Dcucumber.env="${{ inputs.env }}"

            - name: Subida de Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: "Cucumber-Results-${{ inputs.env }}"
                  path: "target/cucumber-reports"
                  retention-days: 1
           